defaults:
  - _self_
  - task: repose
  - alg: control_test
  # - override hydra/launcher: submitit_local


# global defaults 
num_envs: 1 
num_steps: 500
render: true

# ppo defaults
task:
  ppo:
    max_epochs: 2000 
    minibatch_size: 1920
    save_interval: 400
    save_best_after: 100
    num_actors: 1024
    steps_num: 240
    actor_mlp:
      units: 
        - 128
        - 64
        - 32
    critic_mlp:
      units:
        - 64
        - 64
    lr: 3e-4
    lr_schedule: adaptive

  shac:
    lambda: 0.95
    actor_mlp:
      units:
        - 64
        - 64
    critic_mlp:
      units:
        - 64
        - 64
    target_critic_alpha: 0.4
    actor_lr: 1e-3
    critic_lr: 1e-3
    max_epochs: 2000
    save_interval: 400
    steps_num: 32
    betas: 
      - 0.7
      - 0.95

