
[package]
# Semantic Versioning is used: https://semver.org/
version = "0.9.0"
authors = ["NVIDIA"]
title = "Warp"
description="A Python framework for high-performance simulation and graphics programming"
readme  = "docs/README.md"
repository="https://github.com/nvidia/warp"
category = "graph"
keywords = ["kit", "omnigraph", "warp", "simulation"]
changelog="docs/CHANGELOG.md"

preview_image = "data/preview.png"
icon = "data/icon.png"

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py", "*/ogn*"]

[dependencies]
"omni.graph" = {}
"omni.graph.action" = {}
"omni.graph.core" = {}
"omni.graph.nodes" = {}
"omni.kit.actions.core" = {}
"omni.kit.browser.sample" = {optional = true}
"omni.kit.menu.utils" = {optional = true}
"omni.kit.property.usd" = {}
"omni.kit.widget.searchfield" = {}
"omni.kit.widget.text_editor" = {}
"omni.kit.window.property" = {}
"omni.timeline" = {}
"omni.ui" = {}
"omni.usd" = {}
"omni.warp.core" = {}

# Main python module this extension provides, it will be publicly available as "import omni.warp".
[[python.module]]
name = "omni.warp"

[settings]
exts."omni.warp".enable_backward = false
