# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"!\n\x05Model\x12\x10\n\x03xml\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_xml\"\xb8\x01\n\x05State\x12\x11\n\x04time\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x13\n\x07joint_q\x18\x02 \x03(\x01\x42\x02\x10\x01\x12\x14\n\x08joint_qd\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x12\n\x06\x62ody_q\x18\x04 \x03(\x01\x42\x02\x10\x01\x12\x13\n\x07\x62ody_qd\x18\x05 \x03(\x01\x42\x02\x10\x01\x12\x15\n\tjoint_act\x18\x06 \x03(\x01\x42\x02\x10\x01\x12\x12\n\x06\x62ody_f\x18\x07 \x03(\x01\x42\x02\x10\x01\x12\x14\n\x08userdata\x18\x08 \x03(\x01\x42\x02\x10\x01\x42\x07\n\x05_time\"X\n\x0bInitRequest\x12\x14\n\x07task_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x05model\x18\x02 \x01(\x0b\x32\x0c.agent.Model\x12\n\n\x02\x64t\x18\x03 \x01(\x02\x42\n\n\x08_task_id\"\x1f\n\x0cInitResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x11\n\x0fGetStateRequest\"/\n\x10GetStateResponse\x12\x1b\n\x05state\x18\x01 \x01(\x0b\x32\x0c.agent.State\".\n\x0fSetStateRequest\x12\x1b\n\x05state\x18\x01 \x01(\x0b\x32\x0c.agent.State\"\x12\n\x10SetStateResponse\"\r\n\x0bStepRequest\"\x0e\n\x0cStepResponse\"\x0e\n\x0cResetRequest\"\x0f\n\rResetResponse2\x97\x02\n\x05\x41gent\x12/\n\x04Init\x12\x12.agent.InitRequest\x1a\x13.agent.InitResponse\x12;\n\x08GetState\x12\x16.agent.GetStateRequest\x1a\x17.agent.GetStateResponse\x12;\n\x08SetState\x12\x16.agent.SetStateRequest\x1a\x17.agent.SetStateResponse\x12/\n\x04Step\x12\x12.agent.StepRequest\x1a\x13.agent.StepResponse\x12\x32\n\x05Reset\x12\x13.agent.ResetRequest\x1a\x14.agent.ResetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATE'].fields_by_name['joint_q']._options = None
  _globals['_STATE'].fields_by_name['joint_q']._serialized_options = b'\020\001'
  _globals['_STATE'].fields_by_name['joint_qd']._options = None
  _globals['_STATE'].fields_by_name['joint_qd']._serialized_options = b'\020\001'
  _globals['_STATE'].fields_by_name['body_q']._options = None
  _globals['_STATE'].fields_by_name['body_q']._serialized_options = b'\020\001'
  _globals['_STATE'].fields_by_name['body_qd']._options = None
  _globals['_STATE'].fields_by_name['body_qd']._serialized_options = b'\020\001'
  _globals['_STATE'].fields_by_name['joint_act']._options = None
  _globals['_STATE'].fields_by_name['joint_act']._serialized_options = b'\020\001'
  _globals['_STATE'].fields_by_name['body_f']._options = None
  _globals['_STATE'].fields_by_name['body_f']._serialized_options = b'\020\001'
  _globals['_STATE'].fields_by_name['userdata']._options = None
  _globals['_STATE'].fields_by_name['userdata']._serialized_options = b'\020\001'
  _globals['_MODEL']._serialized_start=22
  _globals['_MODEL']._serialized_end=55
  _globals['_STATE']._serialized_start=58
  _globals['_STATE']._serialized_end=242
  _globals['_INITREQUEST']._serialized_start=244
  _globals['_INITREQUEST']._serialized_end=332
  _globals['_INITRESPONSE']._serialized_start=334
  _globals['_INITRESPONSE']._serialized_end=365
  _globals['_GETSTATEREQUEST']._serialized_start=367
  _globals['_GETSTATEREQUEST']._serialized_end=384
  _globals['_GETSTATERESPONSE']._serialized_start=386
  _globals['_GETSTATERESPONSE']._serialized_end=433
  _globals['_SETSTATEREQUEST']._serialized_start=435
  _globals['_SETSTATEREQUEST']._serialized_end=481
  _globals['_SETSTATERESPONSE']._serialized_start=483
  _globals['_SETSTATERESPONSE']._serialized_end=501
  _globals['_STEPREQUEST']._serialized_start=503
  _globals['_STEPREQUEST']._serialized_end=516
  _globals['_STEPRESPONSE']._serialized_start=518
  _globals['_STEPRESPONSE']._serialized_end=532
  _globals['_RESETREQUEST']._serialized_start=534
  _globals['_RESETREQUEST']._serialized_end=548
  _globals['_RESETRESPONSE']._serialized_start=550
  _globals['_RESETRESPONSE']._serialized_end=565
  _globals['_AGENT']._serialized_start=568
  _globals['_AGENT']._serialized_end=847
# @@protoc_insertion_point(module_scope)
