defaults:
  - _self_
  - rewards:
    - action_penalty
    - object_pos_err

name: repose_task

env:
  _target_: warp.envs.ReposeTask
  num_envs: ${resolve_default:1,${...num_envs}}
  episode_length: 500
  rew_params: 
    action_penalty: ${...rewards.action_penalty}
    object_pos_err: ${...rewards.object_pos_err}
